import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import { useEffect, useState } from "react";
import Message from "../components/Message";
import { db } from "../utils/firebase";

export default function Home() {
  const [allPost, setAllPost] = useState([]);
  const getAllPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPost(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getAllPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <h2>See what other people are saying</h2>
        {allPost.map((post) => {
          return <Message key={post.id} {...post}></Message>;
        })}
      </div>
    </div>
  );
}
